# This is a basic workflow to help you get started with Actions

name: updating public dataset running

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      username:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Polly user name'
        # Input has to be provided for the workflow to run
        required: true
      password:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Polly password'
        # Input has to be provided for the workflow to run
        required: true
      how_many_users:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Simulate how many users'
        # Input has to be provided for the workflow to run
        required: true
      each_users_how_many_jobs:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Each users how many jobs'
        # Input has to be provided for the workflow to run
        required: true
      workspace_id:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Polly workspace id to run the simulation'
        # Input has to be provided for the workflow to run
        required: true
      polly_cpu:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'No of cores'
        # Input has to be provided for the workflow to run
        required: true
      polly_memory:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Amount of memory in Gi'
        # Input has to be provided for the workflow to run
        required: true
      time_of_job:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Job run time in seconds'
        # Input has to be provided for the workflow to run
        required: true
      polly_env:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'polly environment options dev test prod'
        # Input has to be provided for the workflow to run
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
