name: Generating public dataset report

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron:  "0 */2 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  running-jobs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.6'

    - name: Installing dependencies and running bust jobs and saving the logs for information 
      env:
        JOBS_ACCESS_KEY: ${{ secrets.JOBS_ACCESS_KEY }}
        JOBS_SECRET_KEY: ${{ secrets.JOBS_SECRET_KEY }}
      run: |
        ls
        pip --version
        pip install -r requirements.txt
        python public_dataset_stats.py "$JOBS_SECRET_KEY" "$JOBS_ACCESS_KEY"
        mv results/index.html ./index.html
        git status
        git add ./index.html
        git status
        git config --global user.email sabu.george@elucidata.io
        git config --global user.name "Sabu George"
        git commit -m "push the updated report"
        git fetch origin gh-pages
        git push origin HEAD:gh-pages
